baseURL = "https://stan.ulbrych.org/"
title = "stan.ulbrych.org"
languageCode = "en-IE"
enableRobotsTXT = false

[params]
  description = "stan.ulbrych.org"
  # XXX add this
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "stan.ulbrych.org"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
